### ISSUE TITLE
arch linux crashes on new mail

### ISSUE THREAD

**Issue by grauschnabel** [a-sk/node-imapnotify#16]
hi there,

I use the arch linux package and it connects to my server, but it crashes on new email
```
[martin@martin-arch org-mode]$ imapnotify 
{"name":"imap_inotify","hostname":"martin-arch","pid":26012,"level":30,"box":"INBOX","msg":"Connected to server","time":"2017-06-13T20:47:48.210Z","v":0}
{"name":"imap_inotify","hostname":"martin-arch","pid":26012,"level":30,"box":"INBOX","msg":"Selecting box","time":"2017-06-13T20:47:48.212Z","v":0}
{"name":"imap_inotify","hostname":"martin-arch","pid":26012,"level":30,"box":"INBOX","msg":"New mail","time":"2017-06-13T20:48:23.436Z","v":0}
/usr/lib/node_modules/imapnotify/node_modules/printf/lib/printf.js:31
  content = str.slice(lastIndex);
               ^

TypeError: Cannot read property 'slice' of undefined
    at tokenize (/usr/lib/node_modules/imapnotify/node_modules/printf/lib/printf.js:31:16)
    at new Formatter (/usr/lib/node_modules/imapnotify/node_modules/printf/lib/printf.js:41:18)
    at module.exports (/usr/lib/node_modules/imapnotify/node_modules/printf/lib/printf.js:459:19)
    at notify (/usr/lib/node_modules/imapnotify/bin/imapnotify:235:17)
    at Connection.<anonymous> (/usr/lib/node_modules/imapnotify/bin/imapnotify:65:9)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at Connection._resUntagged (/usr/lib/node_modules/imapnotify/node_modules/imap/lib/Connection.js:1287:14)
    at Parser.<anonymous> (/usr/lib/node_modules/imapnotify/node_modules/imap/lib/Connection.js:191:10)
    at emitOne (events.js:115:13)
```

Feel free to ask for more information.  The server is a https://github.com/mail-in-a-box/mailinabox

**Comment by a-sk** [comment]
Hi,
that seems to be related to #15.
I don't really have time right now to fix the issue.
You can try the same approach as described in the #15.

> I've currently fixed it simply by putting /usr/bin/true in the onNotifyPost export, but this should probably be handled!

**Comment by grauschnabel** [comment]
I don't use the arch Linux package anymore, the installation via `sudo npm install -g imapnotify` (if I remember correctly) works fine.
