### ISSUE TITLE
ECONNRESET every 30s more or less

### ISSUE THREAD

**Issue by bserrao** [a-sk/node-imapnotify#17]
Hello, 

I'm getting this error every 30s. 

Error: read ECONNRESET\n    at exports._errnoException (util.js:1018:11)\n    at TCP.onread (net.js:572:26)\n  code: 'ECONNRESET',\n  errno: 'ECONNRESET',\n  syscall: 'read',\n  source: 'socket' }","time":"2017-07-22T11:02:13.602Z","v":0}

Any clues on what might be causing this? I'm connecting to a Exchange server trough IMAP.

**Comment by a-sk** [comment]
Hello!

This looks like this issue - https://github.com/mscdex/node-imap/issues/395
Can you try to change tls settings like it's said there?

**Comment by bserrao** [comment]
Hello,
I didn't mention before but i had tried changing the config has mentioned in that issue. I got the same behavior.
I wasn't sure if this issue is related to node-imap implementation or some setting on imap-notify.

BTW if i setup Davmail and connect imap-notify trough Davmail i don't have this issue. It's just a bit overhead since i don't need Davmail for anything else...

Thanks,
