### ISSUE TITLE
"Error: self signed certificate" prevents launch

### ISSUE THREAD

**Issue by gaenserich** [a-sk/node-imapnotify#25]
Trying to run with this config.js:
```javascript
 var child_process = require('child_process');

    function getStdout(cmd) {
        var stdout = child_process.execSync(cmd);
        return stdout.toString().trim();
    }

    exports.host = "imap.gmail.com";
    exports.port = 993;
    exports.tls = true;
    exports.tlsOptions = { "rejectUnauthorized": true };
    exports.username = "mygmailname@gmail.com";
    exports.password = getStdout("/usr/local/bin/gpgpasswordscript.sh");
    exports.onNotify = "systemctl --user start update-mail-%s.service";
    exports.boxes = [ "INBOX", "Other" ];
```
throws this error:
```
{"name":"imap_inotify","hostname":"myhostname","pid":1453,"level":50,"box":"Other","msg":"Error registered","time":"2018-09-25T12:37:53.167Z","v":0} [20/557]
{"name":"imap_inotify","hostname":"myhostname","pid":1453,"level":50,"box":"Other","msg":"{ Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
    at Socket.ondata (internal/wrap_js_stream.js:63:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) code: 'DEPTH_ZERO_SELF_SIGNED_CERT', source: 'socket' }","time":"2018-09-25T12:37:53.170Z","v":0}
{"name":"imap_inotify","hostname":"myhostname","pid":1453,"level":30,"box":"Other","msg":"Restarting immediately","time":"2018-09-25T12:37:53.170Z","v":0}
{"name":"imap_inotify","hostname":"myhostname","pid":1453,"level":50,"box":"INBOX","msg":"Error registered","time":"2018-09-25T12:37:53.176Z","v":0}
{"name":"imap_inotify","hostname":"myhostname","pid":1453,"level":50,"box":"INBOX","msg":"{ Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
    at Socket.ondata (internal/wrap_js_stream.js:63:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) code: 'DEPTH_ZERO_SELF_SIGNED_CERT', source: 'socket' }","time":"2018-09-25T12:37:53.176Z","v":0}
{"name":"imap_inotify","hostname":"myhostname","pid":1453,"level":30,"box":"INBOX","msg":"Restarting immediately","time":"2018-09-25T12:37:53.177Z","v":0}
{"name":"imap_inotify","hostname":"myhostname","pid":1453,"level":50,"box":"Other","msg":"Error registered","time":"2018-09-25T12:37:53.313Z","v":0}
{"name":"imap_inotify","hostname":"myhostname","pid":1453,"level":50,"box":"Other","msg":"{ Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
    at Socket.ondata (internal/wrap_js_stream.js:63:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) code: 'DEPTH_ZERO_SELF_SIGNED_CERT', source: 'socket' }","time":"2018-09-25T12:37:53.314Z","v":0}
{"name":"imap_inotify","hostname":"myhostname","pid":1453,"level":30,"box":"Other","msg":"Scheduling restart in 3000","time":"2018-09-25T12:37:53.314Z","v":0
}
{"name":"imap_inotify","hostname":"myhostname","pid":1453,"level":50,"box":"INBOX","msg":"Error registered","time":"2018-09-25T12:37:53.315Z","v":0}
{"name":"imap_inotify","hostname":"myhostname","pid":1453,"level":50,"box":"INBOX","msg":"{ Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
    at Socket.ondata (internal/wrap_js_stream.js:63:22)
    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) code: 'DEPTH_ZERO_SELF_SIGNED_CERT', source: 'socket' }","time":"2018-09-25T12:37:53.316Z","v":0}
{"name":"imap_inotify","hostname":"myhostname","pid":1453,"level":30,"box":"INBOX","msg":"Scheduling restart in 3000","time":"2018-09-25T12:37:53.316Z","v":0
}
{"name":"imap_inotify","hostname":"myhostname","pid":1453,"level":50,"box":"Other","msg":"Error registered","time":"2018-09-25T12:37:56.457Z","v":0}
{"name":"imap_inotify","hostname":"trauerschwan","pid":1453,"level":50,"box":"Alert","msg":"{ Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
    at Socket.ondata (internal/wrap_js_stream.js:63:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) code: 'DEPTH_ZERO_SELF_SIGNED_CERT', source: 'socket' }","time":"2018-09-25T12:37:56.458Z","v":0}
{"name":"imap_inotify","hostname":"trauerschwan","pid":1453,"level":30,"box":"Other","msg":"Scheduling restart in 6000","time":"2018-09-25T12:37:56.458Z","v":0
}
{"name":"imap_inotify","hostname":"myhostname","pid":1453,"level":50,"box":"INBOX","msg":"Error registered","time":"2018-09-25T12:37:56.494Z","v":0}
{"name":"imap_inotify","hostname":"myhostname","pid":1453,"level":50,"box":"INBOX","msg":"{ Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
    at Socket.ondata (internal/wrap_js_stream.js:63:22)
    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) code: 'DEPTH_ZERO_SELF_SIGNED_CERT', source: 'socket' }","time":"2018-09-25T12:37:56.495Z","v":0}
{"name":"imap_inotify","hostname":"trauerschwan","pid":1453,"level":30,"box":"INBOX","msg":"Scheduling restart in 6000","time":"2018-09-25T12:37:56.495Z","v":0
}{"name":"imap_inotify","hostname":"trauerschwan","pid":1453,"level":50,"box":"Other","msg":"Error registered","time":"2018-09-25T12:38:02.598Z","v":0}
{"name":"imap_inotify","hostname":"trauerschwan","pid":1453,"level":50,"box":"Other","msg":"{ Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
    at Socket.ondata (internal/wrap_js_stream.js:63:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) code: 'DEPTH_ZERO_SELF_SIGNED_CERT', source: 'socket' }","time":"2018-09-25T12:38:02.599Z","v":0}
/usr/lib/node_modules/imapnotify/bin/imapnotify:93
        throw Error('Max retry limit reached')
        ^

Error: Max retry limit reached
    at Connection.<anonymous> (/usr/lib/node_modules/imapnotify/bin/imapnotify:93:15)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at TLSSocket._onError (/usr/lib/node_modules/imapnotify/node_modules/imap/lib/Connection.js:151:10)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

On an ArchLinux machine with the following specs:
imapnotify v0.4.1-9 (from ArchLinux AUR)
node v10.11.0
npm v6.4.1

**Comment by weidtn** [comment]
I have the same error after installing from AUR. I installed it with npm before and it worked. Not sure why as AUR is using npm to install?
